<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');
require_once 'vendor/autoload.php';
use WindowsAzure\Common\ServicesBuilder;

print(custom_U4217);
print(custom_U4221);
?>
